# Generated by Django 2.1.3 on 2018-12-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_posts_posts', '0002_comment_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
