# Generated by Django 2.1.4 on 2018-12-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_posts_posts', '0003_post_total_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-total_likes', 'date')},
        ),
    ]
