# Generated by Django 2.1.3 on 2018-11-30 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('st', 'Student'), ('bm', 'Business man'), ('tr', 'Trader'), ('em', 'Employee'), ('tc', 'Technician')], max_length=25)),
                ('photo', models.ImageField(blank=True, upload_to='Users_Photos')),
                ('address', models.CharField(blank=True, max_length=50)),
                ('school', models.CharField(blank=True, max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=50)),
                ('business_address', models.CharField(blank=True, max_length=50)),
                ('school_address', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
