# Generated by Django 2.1.4 on 2018-12-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_posts_accounts', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('business man', 'Business man'), ('trader', 'Trader'), ('employee', 'Employee'), ('technician', 'Technician')], max_length=25),
        ),
    ]
